OPPONENTS: {


	Colours:	.byte LIGHT_GREEN, BLUE, BROWN, ORANGE, RED, YELLOW, CYAN, PURPLE, BLUE, BROWN, BROWN, DARK_GRAY
				.byte BLACK, RED, WHITE, BLACK, LIGHT_RED, WHITE, DARK_GRAY, BLACK, RED, LIGHT_RED, PURPLE, GREEN
				.byte WHITE, GREEN, BLACK, LIGHT_RED, YELLOW, BLACK, WHITE, YELLOW, BLACK, GRAY, BLUE, WHITE
				.byte PURPLE, GRAY, LIGHT_RED, WHITE, LIGHT_GREEN, LIGHT_RED, YELLOW, RED, WHITE, BLACK, BLACK, BLACK


	Pointers:	.fill 12, 54 + i
				.fill 12, 54 + i
				.fill 12, 54 + i
				.fill 12, 54 + i

	




}